//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biobob
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiomaterEntities9 : DbContext
    {
        public BiomaterEntities9()
            : base("name=BiomaterEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Server_> Server_ { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
        public virtual DbSet<Администратор> Администратор { get; set; }
        public virtual DbSet<Анализатор> Анализатор { get; set; }
        public virtual DbSet<Биоматериал> Биоматериал { get; set; }
        public virtual DbSet<Бухгалтер> Бухгалтер { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Лаборант> Лаборант { get; set; }
        public virtual DbSet<Лист1_> Лист1_ { get; set; }
        public virtual DbSet<Оказанная_услуга> Оказанная_услуга { get; set; }
        public virtual DbSet<Паспорт> Паспорт { get; set; }
        public virtual DbSet<Пациент> Пациент { get; set; }
        public virtual DbSet<Полис> Полис { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Страховая> Страховая { get; set; }
        public virtual DbSet<Тип_пользователя> Тип_пользователя { get; set; }
        public virtual DbSet<Услуги_лаб> Услуги_лаб { get; set; }
    }
}
