//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biobob
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_()
        {
            this.Лист1_ = new HashSet<Лист1_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> lastenter { get; set; }
        public string services { get; set; }
        public Nullable<int> type { get; set; }
        public string Time { get; set; }
        public string foto { get; set; }
        public string email { get; set; }
        public string Телефон { get; set; }
        public Nullable<bool> Статус { get; set; }
        public Nullable<System.TimeSpan> LastActiveTime { get; set; }
    
        public virtual Тип_пользователя Тип_пользователя { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Лист1_> Лист1_ { get; set; }
    }
}
