//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biobob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Лист1_
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> услуги_id { get; set; }
    
        public virtual User_ User_ { get; set; }
    }
}
