//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biobob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оказанная_услуга
    {
        public int Код_оказанной_услуги { get; set; }
        public int Код_услуги { get; set; }
        public Nullable<System.DateTime> Дата_оказания { get; set; }
        public Nullable<int> Код_лаборанта { get; set; }
        public int Код_анализатора { get; set; }
        public string Отчет { get; set; }
    
        public virtual Анализатор Анализатор { get; set; }
        public virtual Лаборант Лаборант { get; set; }
        public virtual Услуги_лаб Услуги_лаб { get; set; }
    }
}
