//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biobob
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public int Код { get; set; }
        public string ФИО { get; set; }
        public string email { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> Тип_пользователя { get; set; }
    }
}
